### ISSUE TITLE
Add a database.json file in a directory called 'api'

### ISSUE THREAD

**Issue by ryanmphill** [NSS-Day-Cohort-64/giffylube#2]
**Given** the browser needs to access data for the user, likes, messages, and posts
**When**  a fetch call is made to the database.json api
**Then** the json server should be able to return data for users, likes, messages, and posts. The data should resemble this:

{
     "users":[
          {
               "id": "#",
               "name": "#",
               "email": "#",
               "password": "#"
          }
     ],
      "messages":[
          {
               "id": "#",
               "userId": "#",
               "recipientId": "#",
               "text": "#",
               "read": "true/false"
          }
     ],
      "posts":[
          {
               "id": "#",
               "userId": "#",
               "title": "#",
               "description": "#",
               "timestamp": "#",
               "imageUrl": "#"
          }
     ],
     "likes":[
          {
               "id": "#",
               "userId": "#",
               "postId": "#",
          }
     ],
}

**Comment by Djmyers1991** [comment]
Finished
